<?php

namespace Tests\Patterns\Structure;

use App\Patterns\Structure\Broker\Client;
use Tests\TestCase;

class BrokerTest extends TestCase
{
    /**
     * Пример работы шаблона Брокер
     */
    public function test_example(): void
    {
        $str = <<<EOD
Calling AddIntegers on 1 and 20...
Client Proxy prepare data...
Client Broker Converting to String...
Client Broker forwarding Bytes to Transfer...
Transporting...
Server Broker transferring data to Server-Side Proxy
Find server method name addIntegers
Returning results...
Transporting back data to client...
Your result is:21
Calling AddIntegers on 2500 and 3000...
Client Proxy prepare data...
Client Broker Converting to String...
Client Broker forwarding Bytes to Transfer...
Transporting...
Server Broker transferring data to Server-Side Proxy
Find server method name addIntegers
Returning results...
Transporting back data to client...
Your result is:5500
Calling getLength on 'Broker in PHP'...
Client Proxy prepare data...
Client Broker Converting to String...
Client Broker forwarding Bytes to Transfer...
Transporting...
Server Broker transferring data to Server-Side Proxy
Find server method name getLength
Returning results...
Transporting back data to client...
Your result is:13

EOD;

        $this->expectOutputString($str);

        // Инициализируем объект клиента
        $client = new Client();

        // Запуск методов клиента к серверу посредством Брокера
        $client->run();
    }
}
